services:
  provider-01-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=provider_01'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5431:5432'
    networks:
      - app-network

  provider-02-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=provider_02'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - app-network

  provider-03-db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=provider_03'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'
    networks:
      - app-network

  provider-01:
    image: 'microservice-provider'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://provider-01-db:5432/provider_01
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - ID=1
    ports:
      - '9081:9081'
    depends_on:
      - provider-01-db
    networks:
      - app-network

  provider-02:
    image: 'microservice-provider'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://provider-02-db:5432/provider_02
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - ID=2
    ports:
      - '9082:9081'
    depends_on:
      - provider-02-db
    networks:
      - app-network

  provider-03:
    image: 'microservice-provider'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://provider-03-db:5432/provider_03
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - ID=3
    ports:
      - '9083:9081'
    depends_on:
      - provider-03-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
